import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bike Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='p-2 bg-blue-950 text-slate-300'>
          <Link href="/">Home</Link>
          <Link href="/blogs">Blogs</Link>
          <Link href="/events">Events</Link>
        </header>
        {children}
        <footer className='p-2 bg-blue-950 text-slate-300'>This is the footer</footer>
        </body>
    </html>
  )
}
