import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "Events default",
    template: "%s | This is the page for event"
  },
  description: 'Generated by create next app',
}

export default function MainPageLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <div>
        <div className="bg-black p-4">Main Page Layout</div>
        {children}
      </div>
    )
  }